version: '3'

services:
  #Image for php
  web:
    build:
      context: images/php
    container_name: php
    restart: unless-stopped
    volumes:
      - ../app:/var/app
      - ../config:/var/config
      - ../core:/var/core
      - ../public:/var/public
      - ../routes:/var/routes
      - ../views:/var/views

  #Image for proxy server
  proxy:
    build:
      context: images/proxy
    container_name: proxy
    image: nginx
    restart: unless-stopped
    ports:
      - ${WEB_PORT:-80}:80
      - "443:443"
    depends_on:
      - web
    volumes:
      - ../public:/var/public
      - ./images/proxy:/etc/nginx/conf.d/

  db:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-db}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD:-password}
      POSTGRES_USER: ${USER_LOGIN:-login}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgres

volumes:
  dbdata:
    driver: local